### ISSUE TITLE
add optical frame into urdf

### ISSUE THREAD

**Issue by Karsten1987** [ros-naoqi/alrosbridge#19]
for the new version of urdf the optical frames do not exist anymore

**Comment by keulYSMB** [comment]
Suprrising, feature has been added in vrabaud/naoqi-bridge@126d32a7513fa9b7e2a3124c6262a6ad262418b7.

**Comment by vrabaud** [comment]
fixed in https://github.com/ros-naoqi/alrosbridge/commit/49ac98033305af5fd20639fb1f7a8c4bc4580077
